### ISSUE TITLE
Maven install failed because of "Could not find artifact com.github.phillip-kruger:jcache-cdi:jar:1.0.0-SNAPSHOT"

### ISSUE THREAD

**Issue by dinhhoang1995** [phillip-kruger/thorntail-jcache-example#1]
Here is the maven install output

> master » mvn clean install                                                                                                                           
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Thorntail JCache                                                   [pom]
[INFO] Thorntail JCache :: Infinispan                                     [jar]
[INFO] Thorntail JCache :: Hazelcast                                      [jar]
[INFO] Thorntail JCache :: Ehcache                                        [jar]
[INFO] Thorntail JCache :: Ignite                                         [jar]
[INFO] Thorntail JCache :: Redis                                          [jar]
[INFO] Thorntail JCache :: Example Application                            [war]
[INFO]
[INFO] --< com.github.phillip-kruger.thorntail.example.jcache:thorntail-jcache >--
[INFO] Building Thorntail JCache 1.0.0-SNAPSHOT                           [1/7]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ thorntail-jcache ---
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ thorntail-jcache ---
[INFO] Installing C:\Users\dhtran\GITHUB\thorntail-jcache-example\pom.xml to C:\Users\dhtran\.m2\repository\com\github\phillip-kruger\thorntail\example\jcache\thorntail-jcache\1.0.0-SNAPSHOT\thorntail-jcache-1.0.0-SNAPSHOT.pom
[INFO]
[INFO] --< com.github.phillip-kruger.thorntail.example.jcache:jcache-infinispan >--
[INFO] Building Thorntail JCache :: Infinispan 1.0.0-SNAPSHOT             [2/7]
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.github.phillip-kruger:jcache-cdi:jar:1.0.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Thorntail JCache 1.0.0-SNAPSHOT:
[INFO]
[INFO] Thorntail JCache ................................... SUCCESS [  0.270 s]
[INFO] Thorntail JCache :: Infinispan ..................... FAILURE [  0.383 s]
[INFO] Thorntail JCache :: Hazelcast ...................... SKIPPED
[INFO] Thorntail JCache :: Ehcache ........................ SKIPPED
[INFO] Thorntail JCache :: Ignite ......................... SKIPPED
[INFO] Thorntail JCache :: Redis .......................... SKIPPED
[INFO] Thorntail JCache :: Example Application ............ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.881 s
[INFO] Finished at: 2019-04-09T10:29:05+03:00
[INFO] ------------------------------------------------------------------------
**[ERROR] Failed to execute goal on project jcache-infinispan: Could not resolve dependencies for project com.github.phillip-kruger.thorntail.example.jcache:jcache-infinispan:jar:1.0.0-SNAPSHOT: Could not find artifact com.github.phillip-kruger:jcache-cdi:jar:1.0.0-SNAPSHOT -> [Help 1]**
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :jcache-infinispan
{ thorntail-jcache-example } master »

**Comment by phillip-kruger** [comment]
Yes, for now you can clone and build https://github.com/phillip-kruger/jcache-cdi locally.

**Comment by phillip-kruger** [comment]
You should also be able to use jcache-cdi from reference impl as well:

<dependency>
            <groupId>org.jsr107.ri</groupId>
            <artifactId>cache-annotations-ri-cdi</artifactId>
            <version>1.1.0</version>
        </dependency>

Removing the one it complains about. I am still busy with something there....
